name: S3 배포 및 CloudFront 캐시 무효화

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: repo 파일 불러오기
        uses: actions/checkout@v5

      - name: npm 패키지 설치하기
        run: npm install

      - name: 빌드하기
        run: npm run build

      - name: AWS Credentials 설정
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ap-southeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 버킷 비우기
        run: aws s3 rm s3://oz-aws-cloudfront --recursive

      - name: S3 버킷에 빌드된 파일 업로드하기
        run: aws s3 cp ./dist s3://oz-aws-cloudfront --recursive

      - name: cloudfront 캐시 무효화하기
        run: |
          aws cloudfront create-invalidation \
          --distribution-id EO4K415P8W31C \
          --paths "/*"
